# Generated by Django 3.2.4 on 2021-06-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_files_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=20)),
                ('score1', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
